remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "St Thomas Drumline"
description: "The (soon to be) official website for the St. Thomas Drumline (Woohoo!)"
github:
  is_project_page: false
